# Generated by Django 5.1.4 on 2025-02-22 20:16

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0122_charfield_null_choices'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('src_ip', models.CharField(max_length=45)),
                ('dst_ip', models.CharField(max_length=45)),
                ('protocol', models.CharField(max_length=10)),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('server_id', models.CharField(max_length=100)),
                ('timestamp', models.FloatField()),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_flows', to='virtualization.virtualmachine')),
            ],
            options={
                'unique_together': {('src_ip', 'dst_ip', 'protocol', 'src_port', 'dst_port', 'server_id')},
            },
        ),
    ]