# Generated by Django 5.1.4 on 2025-02-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_network_flows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficflow',
            name='dst_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dst_traffic_flows', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='trafficflow',
            name='dst_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficflow',
            name='service_port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
       migrations.AlterUniqueTogether(
            name='trafficflow',
            unique_together={('src_ip', 'dst_ip', 'protocol', 'service_port', 'server_id')},
        ),
        migrations.AddField(
            model_name='trafficflow',
            name='src_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='src_traffic_flows', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='trafficflow',
            name='src_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='trafficflow',
            name='dst_port',
        ),
        migrations.RemoveField(
            model_name='trafficflow',
            name='src_port',
        ),
        migrations.RemoveField(
            model_name='trafficflow',
            name='virtual_machine',
        ),
    ]