# Generated by Django 5.1.4 on 2025-02-24 17:39

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0122_charfield_null_choices'),
        ('netbox_network_flows', '0002_alter_trafficflow_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('application_name', models.CharField(max_length=100)),
                ('service_port', models.IntegerField()),
                ('process_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Service Endpoint',
                'verbose_name_plural': 'Service Endpoints',
                'unique_together': {('application_name', 'service_port')},
            },
        ),
    ]