# Generated by Django 5.1.4 on 2025-02-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_network_flows', '0003_serviceendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficflow',
            name='service_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='netbox_network_flows.serviceendpoint'),
        ),
    ]