# Generated by Django 5.1.4 on 2025-02-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_network_flows', '0004_trafficflow_service_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficflow',
            name='service_endpoint',
        ),
        migrations.RemoveField(
            model_name='trafficflow',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='trafficflow',
            name='service_endpoint_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_flows', to='netbox_network_flows.serviceendpoint'),
        ),
    ]